<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNPPkbhe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNPPkbhe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNPPkbhe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNPPkbhe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNPPkbhe\App_KernelDevDebugContainer([
    'container.build_hash' => 'NPPkbhe',
    'container.build_id' => 'd026f2c0',
    'container.build_time' => 1659603780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNPPkbhe');
